controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - Revolute_9
        - Revolute_10
        - Revolute_11
        - Revolute_12
        - Revolute_13
        - Slider_14
        - Slider_15
