# Default initial positions for arm_bot's ros2_control fake system

initial_positions:
  Revolute_10: 0
  Revolute_11: 0
  Revolute_12: 0
  Revolute_13: 0
  Revolute_9: 0
  Slider_14: 0
  Slider_15: 0