ME543_robot_arm_controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  Revolute_9_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_9
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Revolute_10_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_10
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Revolute_11_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_11
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Revolute_12_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_12
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Revolute_13_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute_13
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Slider_14_position_controller:
    type: effort_controllers/JointPositionController
    joint: Slider_14
    pid: {p: 100.0, i: 0.01, d: 10.0}

  Slider_15_position_controller:
    type: effort_controllers/JointPositionController
    joint: Slider_15
    pid: {p: 100.0, i: 0.01, d: 10.0}
