controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController
      joints:
        - joint1
      state_publish_rate: 50
      constraints:
        goal_time: 0.2
        stopped_velocity_tolerance: 0.01
      gains:
        joint1:
          p: 100.0
          i: 0.1
          d: 0.01
